# .github/workflows/on-commit.yml

# Nome do fluxo de trabalho que aparecerá na aba "Actions" do GitHub
name: CI on Commit

# Define o gatilho (trigger) do fluxo de trabalho
on:
  push:
    branches: [ main ] # Executa apenas em commits na branch 'main'

# Define os "trabalhos" (jobs) a serem executados
jobs:
  build-and-test:
    # Define o ambiente virtual onde o trabalho será executado
    runs-on: ubuntu-latest

    # Define a sequência de passos
    steps:
      # Passo 1: Clonar o repositório
      # A action 'checkout' clona seu repositório e troca para o commit/branch correto
      - name: Checkout repository
        uses: actions/checkout@v4

      # Passo 2: Instalar o interpretador da linguagem (Node.js)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Você pode especificar a versão do Node

      # Passo 3: Instalar as dependências do projeto
      # 'npm ci' é mais rápido e seguro para ambientes de CI do que 'npm install'
      - name: Install dependencies
        run: npm ci

      # Passo 4: Executar os testes da aplicação
      - name: Run tests
        run: npm test