# .github/workflows/on-pull-request.yml

# Nome do fluxo de trabalho
name: CI on Pull Request

# Define o gatilho
on:
  pull_request:
    branches: [ main ] # Executa quando um PR é aberto (ou atualizado) para a branch 'main'

# O resto do arquivo é IDÊNTICO ao anterior, pois os passos são os mesmos.
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test